# this file contains prompt texts
# each prompt should contain: system_prompt, user_prompt_shared, expected_schema

[match_synonym_definitions]

system_prompt = "You are teaching Mandarin Chinese to adult English native speakers, using both traditional (繁體字) and simplified characters (简体字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for two possible synonyms, word_a and word_b. Each definition has an id number (Dx).
Provide those pairs of definitions from both words which are most similar in meaning.
Only include pairs of actual synonyms. Definitions shall not be included in multiple pairs.
For each pair also provide:
- a score indicating how similar the definitions actually are (also considering usage in different contexts)
- a short, dictionary-like explanation in English, highlighting the differences in usage

If there are no matching pairs of synonyms, return one pair with definition ids 0 and score 5.

Possible similarity scores:
1 identical, interchangeable in all contexts
2 quite similar, interchangeable in some contexts
3 roughly similar, but not interchangeable
4 small overlap, but mostly different
5 not a synonym

Output a valid csv (comma separated values) using one row for each pair, each row in the format described below (columns separated with semicolon ";").
Do not add any text before or after the csv output. The definition ids should be output as numbers, without the preceding D.

csv format:
'''

expected_schema = "word_a;definition id number for word_a;word_b;definition id number for word_b;score (1-5);explanation"


[match_antonym_definitions]

system_prompt = "You are teaching Mandarin Chinese to adult English native speakers, using both traditional (繁體字) and simplified characters (简体字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for two possible antonyms, word_a and word_b. Each definition has an id number (Dx).
Provide the one pair of definitions from both words which fits best into one of the antonym categories described below.
Additionally provide
- what category of antonym it is (according to table below)
- a short, dictionary-like explanation in English, highlighting why the definitions can be considered antonyms of the chosen category

Possible categories of antonyms:
1 Gradable antonyms: opposites on a continuous spectrum (young-old, heavy-light)
2 Complementary antonyms: opposites with no continuous spectrum (left-right, even-odd)
3 Relational antonyms: a relationship from opposite points of view (doctor-patient, come-go, parent-child)
4 No antonym

Output a valid csv (comma separated values) using the format described below (one row with columns separated with semicolon ";").
Do not add any text before or after the csv output. The definition ids should be output as numbers, without the preceding D.

csv format:
'''

expected_schema = "word_a;definition id number for word_a;word_b;definition id number for word_b;antonym category (1-4);explanation"


[find_collocations]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = '''
Complete the list below with up to 10 most common and idiomatic collocations for each word in traditional characters.
The collocations should be separated by commas. Only output the list of words without any additional explanations etc.
Each collocation could commonly appear before or after the word, only list the collocations, without the provided word.

'''

expected_schema = "小提琴:拉,家,演奏,弓,琴弦"


[match_collocations_DRAFT]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = ''' TODO filter collocations before and only provide valid ones to match definitions
Provided below are definitions from a dictionary for a Chinese word (WORD) and possible collocations (COLLOCATION_A-Z),
which were derived using statistical analysis of a corpus of subtitles (from movies/tv series). Each definition has an id number (Dx).
From the provided options, identify the subset of useful collocations for students to learn and practice so that their Chinese sounds more idiomatic.
Ignore entries which are not real collocations and are merely a statistical artifact due to the limited size of the corpus,
shortcomings in the statistical analysis or are common grammatical words etc.
The identified collocations should reflect common usage in spoken language.
It could also happen that no suitable collocations are available. In that case the output should be a single yaml object:
COLLOCATIONS: 0

For each identified collocation, provide one pair of definitions, one from the word and one from the collocation, indicating how they would be used together.
Also provide an example sentence in traditional characters (繁體字) with an English translation, to illustrate the usage.

Output the result as a valid yaml object without any additional text before or after.

Example prompt:

WORD:
小提琴
- D1 [music] violin

COLLOCATION_C:
拉
...
- D6 to play (a bowed instrument, an accordion, etc.)
...

Example yaml output:

COLLOCATION_C:
  ch: 我學過拉小提琴。
  en: I have learned how to play the violin.
  word: 小提琴
  word_def_id: D1
  col: 拉
  col_def_id: D6

The format shall be a valid yaml object with one object for each identified collocation:
'''

expected_schema = '''
COLLOCATION_X: (identifier of the collocation)
  ch: (example sentence in traditional characters)
  en: (translation of the example sentence in American English)
  word: (the word which the collocation refers to)
  word_def_id: (the id of the definition of the word used with collocation)
  col: (the collocation)
  col_def_id: (the id of the definition of the collocation used with the word)
'''