# this file contains prompt texts
# each prompt should contain: system_prompt, user_prompt_shared, expected_schema

[match_synonym_definitions]

system_prompt = "You are teaching Mandarin Chinese to adult English native speakers, using both traditional (繁體字) and simplified characters (简体字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for two possible synonyms, word_a and word_b. Each definition has an id number (Dx).
Provide those pairs of definitions from both words which are most similar in meaning.
Only include pairs of actual synonyms. Definitions shall not be included in multiple pairs.
For each pair also provide:
- a score indicating how similar the definitions actually are (also considering usage in different contexts)
- a short, dictionary-like explanation in English, highlighting the differences in usage

If there are no matching pairs of synonyms, return one pair with definition ids 0 and score 5.

Possible similarity scores:
1 identical, interchangeable in all contexts
2 quite similar, interchangeable in some contexts
3 roughly similar, but not interchangeable
4 small overlap, but mostly different
5 not a synonym

Output a valid csv (comma separated values) using one row for each pair, each row in the format described below (columns separated with semicolon ";").
Do not add any text before or after the csv output. The definition ids should be output as numbers, without the preceding D.

csv format:
'''

expected_schema = "word_a;definition id number for word_a;word_b;definition id number for word_b;score (1-5);explanation"


[match_antonym_definitions]

system_prompt = "You are teaching Mandarin Chinese to adult English native speakers, using both traditional (繁體字) and simplified characters (简体字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for two possible antonyms, word_a and word_b. Each definition has an id number (Dx).
Provide the one pair of definitions from both words which fits best into one of the antonym categories described below.
Additionally provide
- what category of antonym it is (according to table below)
- a short, dictionary-like explanation in English, highlighting why the definitions can be considered antonyms of the chosen category

Possible categories of antonyms:
1 Gradable antonyms: opposites on a continuous spectrum (young-old, heavy-light)
2 Complementary antonyms: opposites with no continuous spectrum (left-right, even-odd)
3 Relational antonyms: a relationship from opposite points of view (doctor-patient, come-go, parent-child)
4 No antonym

Output a valid csv (comma separated values) using the format described below (one row with columns separated with semicolon ";").
Do not add any text before or after the csv output. The definition ids should be output as numbers, without the preceding D.

csv format:
'''

expected_schema = "word_a;definition id number for word_a;word_b;definition id number for word_b;antonym category (1-4);explanation"


[find_collocations]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = '''
Complete the list below with up to 10 most common and idiomatic collocations for each word in traditional characters.
The collocations should be separated by commas. Only output the list of words without any additional explanations etc.
Each collocation could commonly appear before or after the word, only list the collocations, without the provided word.

'''

expected_schema = "小提琴:拉,家,演奏,弓,琴弦"


[match_collocations]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for a Chinese word and its collocations. Each definition has an id number (Dx).

For each collocation provide:
- an example sentence in traditional characters (繁體字) with an English translation to illustrate the usage, use spaces to separate words in the Chinese sentence

- the one pair of definition ids, one id from the word and one id from the collocation, which best represents how they would be used together

- optional: a tag which best characterizes the word-collocation pair using one of the options below:
    - grammatical: the collocation usually has a grammatical function (pronoun, particle, etc.)
    - synonym: both have similar meanings
    - antonym: both have opposite meanings
    - classifier: the collocation is a measure word / classifier for the word

Example prompt:

word:
小提琴
- D1 [music] violin

collocations:
拉
...
- D6 to play (a bowed instrument, an accordion, etc.)
...

Example yaml output:

拉:
  ch: 我 學 過 拉 小提琴。
  en: I have learned how to play the violin.
  word_def_id: D1
  col_def_id: D6

The format shall be a valid yaml object with one object for each collocation and no additional text before or after:
'''

expected_schema = '''搭配: # (the collocation word)
  ch: # (example sentence in traditional characters)
  en: # (translation of the example sentence in American English)
  tag: # (optional, tag picked from the given set of options)
  word_def_id: # (the definition id of the word when used with the collocation)
  col_def_id: # (the definition id of the collocation when used with the word)
'''


[match_decomposition]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers, using both traditional (繁體字) and simplified characters (简体字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for a Chinese word and all its possible decompositions into other words and characters with their definitions.
Each definition has an id number (Dx).

Identify the components (words or characters) from the subset which represent the best semantic decomposition of the word or explain the word best.
The identified components put together should form the original word.

If a definition of a component contributes to the main meanings of the decomposed word, provide the definition id for that component.

In some cases the meanings of the components might not contribute to the meanings of the word. In that case provide the definition id D0 for that component.

The output should consist of all components with their definition ids (or D0) separated by semicolons (;).
Each component and its definition id should be joined by a '#' like so: 東西／东西#D1

Do not add any further text before or after, no further explanations are necessary.

Example prompt:

word:
英雄所見略同／英雄所见略同
- D1 Great minds think alike.

possible components:
英雄
...
- D2 [figuratively, literally, martial-arts] hero
...

所
...
- D4 Prefix attached to verbs to form noun phrases, indicating the patient of the verb, similar to a passive participle.
...

見／见
...
- D6 opinion, idea, view
...

略同
- D1 to be about the same; to be similar

Expected output:
'''

expected_schema = '''英雄#D2;所#D4;見／见#D6;略同#D1'''


[identify_definitions_in_subtitles]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = '''
Provided below are definitions from a dictionary for a Chinese word. Each definition has an id number (Dx).

The goal is, based on the excerpts below, to identify those definitions which are used in modern, spoken Mandarin.

The numbered text excerpts are lines of subtitles from movies and TV series. Each excerpt is independent.
For each excerpt, provide (separated by semicolons):
- the number of the excerpt
- the English translation of the requested word in the context of the snippet
- the id number of the definition which fits best to the usage of the given word in that context

If no definition fits, provide the id D0. If multiple definitions could fit, separate the ids by comma (e.g. 3:D4,D8).

Do not add any additional explanations or translations.

Example:

word:
左右
- D1 left and right
- D2 left and right sides; both sides
- D3 entourage; retinue; attendants
- D4 about; or so; or thereabouts; around; approximately
- D5 to control; to manipulate; to influence

...
9
專家表示
低溫狀態將持續一週左右
體感濕冷
...

Response:
'''

expected_schema = '''
9;around;D4
'''


[identify_stand_alone_definitions_of_chars]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

user_prompt_shared = '''
Chinese characters can have different meanings, depending on whether they are used as part of a word or independently as a word on its own.
From the dictionary entry below, identify those definitions which refer to the usage as a stand-alone word in modern, spoken Mandarin.
For definitions which refer to the usage as a stand-alone word in modern, spoken Mandarin, only provide the character on its own.
For definitions which refer to the usage as a bound form, provide one common example word for that usage (in traditional characters).
The output format shall be the definition id and the Chinese character or word, separated by a colon. Each definition id on a separate line.

Example:

word:
所
- D1 place; location
- D2 establishment for a particular function; institution
- D4 Prefix attached to verbs to form noun phrases, indicating the patient of the verb, similar to a passive participle.
- D5 Used with 為／为 (wéi) or 被 (bèi) to form the passive voice.
- D3 Classifier for buildings, schools, hospitals, etc.

expected response:
'''

expected_schema = '''
D1:住所
D2:派出所
D4:所得
D5:所
D3:所
'''

[identify_spoken_definitions_of_words]

system_prompt = "You are a teacher, teaching Mandarin Chinese to adult English native speakers using traditional characters (繁體字)."

# note: verify result by checking if word is in short example

user_prompt_shared = '''
From the dictionary entry below, identify those definitions which are used in modern, standard, spoken Mandarin
in China (普通話) or Taiwan (國語).
For each definition, provide (separated by semicolon):
- the definition id
- a short example for the usage of this definition in traditional characters (if not possible, just the word itself)
- a rating:
  - standard: commonly used in standard, spoken language
  - written: only used in written language, not in spoken language
  - non-standard: not used in standard, spoken mandarin (could be colloquial, dialectal, regional, etc.)
  - unknown: no clear rating possible

Do not add any additional formatting, explanations or translations.

Example:

word:
蝴蝶
- D1 butterfly
- D2 [Hokkien] hinge (device for the pivoting of a door)

expected response:
'''

expected_schema = '''
D1;蝴蝶飛來飛去;standard
D2;蝴蝶;non-standard
'''